server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices-realm

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: product-service
              uri: http://product-service:8081
              predicates:
                - Path=/products/**
              filters:
                - PreserveHostHeader

            - id: order-service
              uri: http://order-service:8082
              predicates:
                - Path=/orders/**
              filters:
                - PreserveHostHeader
